# recipes api for swagger

paths:
  /recipes:
    post:
      tags:
        - recipes
      summary: 칵테일 레시피 작성
      description: ''
      operationId: createRecpie
      requestBody:
        required: true
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createRecipe'
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/{cocktailId}:
    get:
      tags:
        - recipes
      summary: 칵테일 레시피 가져오기(수정을 위해)
      description: ''
      operationId: getRecipe
      parameters:
        - in: path
          name: cocktailId
          type: integer
          example: 3
          description: 가져올 레시피 id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getRecipe'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

    delete:
      tags:
        - recipes
      summary: 칵테일 레시피 삭제
      description: ''
      operationId: deleteRecpie
      parameters:
        - in: path
          name: cocktailId
          description: 게시글 ID
          example: 3
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/update/{cocktailId}:
    post:
      tags:
        - recipes
      summary: 칵테일 레시피 수정
      description: PUT 메소드로는 이미지 전송이 안돼서 POST로 합니다
      operationId: updateRecipe
      parameters:
        - in: path
          name: cocktailId
          type: integer
          example: 3
          description: 변경하려는 레시피 id
      requestBody:
        required: true
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRecipe'

  /recipes/list/filter/{page}:
    get:
      tags:
        - recipes
      summary: 칵테일 레시피 목록
      description: ''
      operationId: getRecipeList
      parameters:
        - in: path
          name: page
          type: integer
          description: page number
          example: 1
          required: true
        - in: query
          name: alcoholic
          type: string
          description: 알콜수준, 0-낮음, 1-보통, 2-높음
          example: '[0,1,2]'
        - in: query
          name: color
          type: string
          description: 색상, 최대3개, 1-빨강 2-주황 3-노랑 4-초록 5-파랑 6-보라 7-분홍 8-검정 9-갈색 10-회색 11-흰색 12-무색
          example: '[1,2,3]'
        - in: query
          name: search
          type: string
          description: 검색키워드
          example: 진
        - in: query
          name: sort
          type: string
          description: 정렬기준(일단은 기본-추천순이고 sort query로 new를 줬을 때만 최신순입니다)
          example: new
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getRecipeList'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/detail/{cocktailId}:
    get:
      tags:
        - recipes
      summary: 칵테일 레시피 상세
      description: ''
      operationId: GetRecipeDetail
      parameters:
        - in: path
          name: cocktailId
          type: integer
          description: 칵테일 레시피 ID
          example: 10
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipeDetail'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/detail/review/{cocktailId}:
    get:
      tags:
        - recipes
      summary: 칵테일 레시피에 대한 리뷰 상세
      description: ''
      operationId: GetRecipeDetailReview
      parameters:
        - in: path
          name: cocktailId
          type: integer
          description: 칵테일 레시피 ID
          example: 10
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipeDetailReview'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/image/{cocktailId}:
    get:
      tags:
        - recipes
      summary: 칵테일 레시피 이미지
      description: ''
      operationId: GetRecipeImage
      parameters:
        - in: path
          name: cocktailId
          type: integer
          description: 칵테일 레시피 ID
          example: 11000
      responses:
        '200':
          description: ''
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/like/{cocktailId}:
    post:
      tags:
        - recipes
      summary: 칵테일 레시피 좋아요/좋아요 취소
      description: 이미 좋아요 했는지 확인해서 좋아요 혹은 좋아요취소, Success시 liked에 좋아요인지/최소인지와 like에 like 개수를 return합니다
      operationId: LikeCocktail
      parameters:
        - in: path
          name: cocktailId
          type: integer
          description: 칵테일 레시피 ID
          example: 11000
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeUnlikeSuccess'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'

  /recipes/report/{cocktailId}:
    post:
      tags:
        - recipes
      summary: 칵테일 레시피 신고
      description: status 200에서 success-true이면 신고 성공, false이면 이미 신고한 상태
      operationId: ReportCocktail
      parameters:
        - in: path
          name: cocktailId
          type: integer
          description: 칵테일 레시피 ID
          example: 11000
      requestBody:
        required: true
        description: ''
        content:
          application/json:
            schema:
              properties:
                report:
                  type: integer
                  example: 1
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fail'
